# Generated by Django 2.1 on 2019-01-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateField()),
                ('shop', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('account', models.IntegerField(default=0)),
            ],
        ),
    ]
